name = "MyExamplePkg"
uuid = "07eac608-88dd-48bd-94fc-19e8a2bd78eb"
authors = ["Matt Camp"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
